version: "3"

services:
  goalem-landing:
    image: ${IMAGE}
    container_name: goalem-landing-${BRANCH}
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.goalem_front_${BRANCH}.rule=Host(`${URL}`)"
      - "traefik.http.services.goalem_front_${BRANCH}.loadbalancer.server.port=80"
      - "traefik.http.routers.goalem_front_${BRANCH}.entrypoints=http"
      - "traefik.http.routers.goalem_front_${BRANCH}.tls.certresolver=le"
      - "traefik.http.routers.goalem_front_${BRANCH}.entrypoints=https"

networks:
  default:
    external:
      name: goalem

